GET http://localhost:9000/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhvbmdxaUBnbWFpbC5jb20iLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTYxMzgzNDIyN30.F4_1qRUfAieIdGpjkMVkrndQxDHrZMib2Xr5txX8cL0
###

POST http://localhost:9000/login
Content-Type: application/json

{
    "email": "hongqi@gmail.com",
    "password": "1234"
}